POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test",
    "password": "test"
}
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test",
    "password": "test"
}
###

POST http://localhost:8080/api/goals
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5MjMxODEwNjRkOWZmNTIyNDc4ZTg3NyIsImVtYWlsIjoidGVzdCIsIm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNDk1NjQzNjc5LCJleHAiOjE0OTU2NDcyNzl9.lEuv3AdnH6-TUk6AgufcuUxGJ1VfZxEOGsFxp85ufl8

{
    "name": "test",
    "type": "wealth"
}
###


